---
- name: Create monitoring directory
  ansible.builtin.file:
    path: /opt/cloud-platform/monitoring
    state: directory
    mode: '0755'


- name: Copy monitoring docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/cloud-platform/monitoring/docker-compose.yml
    mode: '0644'


- name: Start monitoring stack
  community.docker.docker_compose_v2:
    project_src: /opt/cloud-platform/monitoring
    state: present
