---
- name: Create cloud platform directory
  ansible.builtin.file:
    path: /opt/cloud-platform
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'


- name: Copy Docker Compose application file
  ansible.builtin.copy:
    src: applications.yml
    dest: /opt/cloud-platform/applications.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'


- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/cloud-platform
    files:
      - applications.yml
    state: present
